# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UtrCli < Formula
  desc "A command line interface for the [Universal Tennis Rating](https://www.myutr.com/) system. This tool allows you to quickly lookup Tennis or PickleBall players and view their match history."
  homepage "https://github.com/lineville/utr-cli"
  version "0.0.8"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lineville/utr-cli/releases/download/v0.0.8/utr-cli_Darwin_arm64.tar.gz"
      sha256 "c9e33212fd43e59b3ac90ddaee23867981fabcad7e76daade6ec3936faca87f6"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lineville/utr-cli/releases/download/v0.0.8/utr-cli_Darwin_x86_64.tar.gz"
      sha256 "5ba32b44bdfb1beb4160aaa168d8574254e94fc2d24de98808a5b2bfa79fadfb"

      def install
        bin.install "utr-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lineville/utr-cli/releases/download/v0.0.8/utr-cli_Linux_armv6.tar.gz"
      sha256 "17f7df86d81aea1defc836deb0b6aebc62628dfa9a9c20a3b672094f283258e7"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lineville/utr-cli/releases/download/v0.0.8/utr-cli_Linux_x86_64.tar.gz"
      sha256 "222196444737ac48a6476c3d83de6a5ad282cc04cc7109f78ad46bb6347d5835"

      def install
        bin.install "utr-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lineville/utr-cli/releases/download/v0.0.8/utr-cli_Linux_arm64.tar.gz"
      sha256 "b74d278af028f106a2667d79b7843edada917df90a8874945ef763bb55082d02"

      def install
        bin.install "utr-cli"
      end
    end
  end
end
